[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-local-folder = ["handlers", "keyboards", "states"]

[tool.ruff]
line-length = 80
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".env",
    "venv",
    "env",
    ".vscode",
]
